name: Jekyll site CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      # running jekyll build in docker. Using a different destination folder and two config files
      # config_prod overrides values in config which are for development
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --destination _prod_site/ --config _config.yml"
    - name: Setup Environment.
      env:
        known_hosts: ${{ secrets.KNOWN_HOSTS }} 
      run: |
        sudo apt-get install -y lftp
        mkdir -p ~/.ssh/
        echo $known_hosts >> ~/.ssh/known_hosts
    - name: Upload site to FTP.
      env: 
        ftp_location: ${{ secrets.FTP_LOCATION }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }} 
        ftp_path: ${{ secrets.FTP_PATH }} 
      # mirror -R uploads files to the folder to the FTP server
      # timeout and max-tries set to make it stop when the upload doesn't work instead of retrying
      run: |
        lftp ftp://$ftp_username:$ftp_password@$ftp_location  -e "set cmd:at-exit; set net:timeout 30; set net:max-retries 3; mirror --verbose --no-perms -R _prod_site //; bye"
